/******************************************************************************
 * Copyright (c) 1998 Lawrence Livermore National Security, LLC and other
 * HYPRE Project Developers. See the top-level COPYRIGHT file for details.
 *
 * SPDX-License-Identifier: (Apache-2.0 OR MIT)
 ******************************************************************************/

#ifndef hypre_SSTRUCT_LS_HEADER
#define hypre_SSTRUCT_LS_HEADER

#include <stdlib.h>
#include <stdio.h>
#include <math.h>

#include <NALU_HYPRE_config.h>

#include "NALU_HYPRE_sstruct_ls.h"

#include "_hypre_utilities.h"
#include "krylov.h"
#include "_hypre_struct_ls.h"
#include "_hypre_sstruct_mv.h"
#include "_hypre_parcsr_ls.h"
#include "multivector.h"

#ifdef __cplusplus
extern "C" {
#endif

/*--------------------------------------------------------------------------
 * hypre_SStructOwnInfo data structure
 * This structure is for the coarsen fboxes that are on this processor,
 * and the cboxes of cgrid/(all coarsened fboxes) on this processor (i.e.,
 * the coarse boxes of the composite cgrid (no underlying) on this processor).
 *--------------------------------------------------------------------------*/
#ifndef hypre_OWNINFODATA_HEADER
#define hypre_OWNINFODATA_HEADER


typedef struct
{
   NALU_HYPRE_Int             size;

   hypre_BoxArrayArray  *own_boxes;    /* size of fgrid */
   NALU_HYPRE_Int           **own_cboxnums; /* local cbox number- each fbox
                                          leads to an array of cboxes */

   hypre_BoxArrayArray  *own_composite_cboxes;  /* size of cgrid */
   NALU_HYPRE_Int             own_composite_size;
} hypre_SStructOwnInfoData;


/*--------------------------------------------------------------------------
 * Accessor macros: hypre_SStructOwnInfoData;
 *--------------------------------------------------------------------------*/

#define hypre_SStructOwnInfoDataSize(own_data)       ((own_data) -> size)
#define hypre_SStructOwnInfoDataOwnBoxes(own_data)   ((own_data) -> own_boxes)
#define hypre_SStructOwnInfoDataOwnBoxNums(own_data) \
((own_data) -> own_cboxnums)
#define hypre_SStructOwnInfoDataCompositeCBoxes(own_data) \
((own_data) -> own_composite_cboxes)
#define hypre_SStructOwnInfoDataCompositeSize(own_data) \
((own_data) -> own_composite_size)

#endif
/*--------------------------------------------------------------------------
 * hypre_SStructRecvInfo data structure
 *--------------------------------------------------------------------------*/
#ifndef hypre_RECVINFODATA_HEADER
#define hypre_RECVINFODATA_HEADER


typedef struct
{
   NALU_HYPRE_Int             size;

   hypre_BoxArrayArray  *recv_boxes;
   NALU_HYPRE_Int           **recv_procs;

} hypre_SStructRecvInfoData;

#endif
/*--------------------------------------------------------------------------
 * hypre_SStructSendInfo data structure
 *--------------------------------------------------------------------------*/
#ifndef hypre_SENDINFODATA_HEADER
#define hypre_SENDINFODATA_HEADER


typedef struct
{
   NALU_HYPRE_Int             size;

   hypre_BoxArrayArray  *send_boxes;
   NALU_HYPRE_Int           **send_procs;
   NALU_HYPRE_Int           **send_remote_boxnums;

} hypre_SStructSendInfoData;

#endif
typedef struct
{
   hypre_IJMatrix    *Face_iedge;
   hypre_IJMatrix    *Element_iedge;
   hypre_IJMatrix    *Edge_iedge;

   hypre_IJMatrix    *Element_Face;
   hypre_IJMatrix    *Element_Edge;

} hypre_PTopology;

/******************************************************************************
 *
 * Header info for the Maxwell solver
 *
 *****************************************************************************/

#ifndef hypre_MAXWELL_HEADER
#define hypre_MAXWELL_HEADER

/*--------------------------------------------------------------------------
 * hypre_MaxwellData:
 *--------------------------------------------------------------------------*/

typedef struct
{
   MPI_Comm                comm;

   NALU_HYPRE_Real              tol;
   NALU_HYPRE_Int               max_iter;
   NALU_HYPRE_Int               rel_change;
   NALU_HYPRE_Int               zero_guess;
   NALU_HYPRE_Int               ndim;

   NALU_HYPRE_Int               num_pre_relax;  /* number of pre relaxation sweeps */
   NALU_HYPRE_Int               num_post_relax; /* number of post relaxation sweeps */

   NALU_HYPRE_Int               constant_coef;

   hypre_Index            *rfactor;

   hypre_SStructGrid     **egrid_l;

   NALU_HYPRE_IJMatrix          Aen;
   hypre_ParCSRMatrix    **Aen_l;

   /* these will be extracted from the amg_data structure. Note that there is no grid
      underlying these matrices and vectors if they are generated by the amg_setup.
      So, will be stored as Parcsr_matrices and Par_vectors. */
   hypre_SStructMatrix    *Ann;
   hypre_SStructVector    *bn;
   hypre_SStructVector    *xn;

   void                   *amg_vdata;
   hypre_ParCSRMatrix    **Ann_l;
   hypre_SStructStencil  **Ann_stencils;
   hypre_ParCSRMatrix    **Pn_l;
   hypre_ParCSRMatrix    **RnT_l;
   hypre_ParVector       **bn_l;
   hypre_ParVector       **xn_l;
   hypre_ParVector       **resn_l;
   hypre_ParVector       **en_l;
   hypre_ParVector       **nVtemp_l;
   hypre_ParVector       **nVtemp2_l;
   NALU_HYPRE_Int             **nCF_marker_l;
   NALU_HYPRE_Real             *nrelax_weight;
   NALU_HYPRE_Real             *nomega;
   NALU_HYPRE_Int               nrelax_type;
   NALU_HYPRE_Int               node_numlevels;

   hypre_ParCSRMatrix     *Tgrad;
   hypre_ParCSRMatrix     *T_transpose;

   /* edge data structure. These will have grids. */
   NALU_HYPRE_Int               edge_maxlevels;
   NALU_HYPRE_Int               edge_numlevels;
   hypre_ParCSRMatrix    **Aee_l;
   hypre_ParVector       **be_l;
   hypre_ParVector       **xe_l;
   hypre_ParVector       **rese_l;
   hypre_ParVector       **ee_l;
   hypre_ParVector       **eVtemp_l;
   hypre_ParVector       **eVtemp2_l;
   NALU_HYPRE_Int             **eCF_marker_l;
   NALU_HYPRE_Real             *erelax_weight;
   NALU_HYPRE_Real             *eomega;
   NALU_HYPRE_Int               erelax_type;

   /* edge data structure. These will have no grid. */
   hypre_IJMatrix        **Pe_l;
   hypre_IJMatrix        **ReT_l;
   NALU_HYPRE_Int             **BdryRanks_l;
   NALU_HYPRE_Int              *BdryRanksCnts_l;

   /* edge-node data structure. These will have grids. */
   NALU_HYPRE_Int               en_numlevels;

   /* log info (always logged) */
   NALU_HYPRE_Int               num_iterations;
   NALU_HYPRE_Int               time_index;

   /* additional log info (logged when `logging' > 0) */
   NALU_HYPRE_Int               print_level;
   NALU_HYPRE_Int               logging;
   NALU_HYPRE_Real             *norms;
   NALU_HYPRE_Real             *rel_norms;

} hypre_MaxwellData;

#endif
typedef struct
{
   NALU_HYPRE_Int row;

   NALU_HYPRE_Int ncols;
   NALU_HYPRE_BigInt *cols;
   NALU_HYPRE_Real   *data;

} hypre_MaxwellOffProcRow;


/* eliminate_rowscols.c */
NALU_HYPRE_Int hypre_ParCSRMatrixEliminateRowsCols ( hypre_ParCSRMatrix *A, NALU_HYPRE_Int nrows_to_eliminate,
                                                NALU_HYPRE_Int *rows_to_eliminate );
NALU_HYPRE_Int hypre_CSRMatrixEliminateRowsColsDiag ( hypre_ParCSRMatrix *A,
                                                 NALU_HYPRE_Int nrows_to_eliminate, NALU_HYPRE_Int *rows_to_eliminate );
NALU_HYPRE_Int hypre_CSRMatrixEliminateRowsOffd ( hypre_ParCSRMatrix *A, NALU_HYPRE_Int nrows_to_eliminate,
                                             NALU_HYPRE_Int *rows_to_eliminate );
NALU_HYPRE_Int hypre_CSRMatrixEliminateColsOffd ( hypre_CSRMatrix *Aoffd, NALU_HYPRE_Int ncols_to_eliminate,
                                             NALU_HYPRE_Int *cols_to_eliminate );

/* fac_amr_fcoarsen.c */
NALU_HYPRE_Int hypre_AMR_FCoarsen ( hypre_SStructMatrix *A, hypre_SStructMatrix *fac_A,
                               hypre_SStructPMatrix *A_crse, hypre_Index refine_factors, NALU_HYPRE_Int level );

/* fac_amr_rap.c */
NALU_HYPRE_Int hypre_AMR_RAP ( hypre_SStructMatrix *A, hypre_Index *rfactors,
                          hypre_SStructMatrix **fac_A_ptr );

/* fac_amr_zero_data.c */
NALU_HYPRE_Int hypre_ZeroAMRVectorData ( hypre_SStructVector *b, NALU_HYPRE_Int *plevels,
                                    hypre_Index *rfactors );
NALU_HYPRE_Int hypre_ZeroAMRMatrixData ( hypre_SStructMatrix *A, NALU_HYPRE_Int part_crse,
                                    hypre_Index rfactors );

/* fac.c */
void *hypre_FACCreate ( MPI_Comm comm );
NALU_HYPRE_Int hypre_FACDestroy2 ( void *fac_vdata );
NALU_HYPRE_Int hypre_FACSetTol ( void *fac_vdata, NALU_HYPRE_Real tol );
NALU_HYPRE_Int hypre_FACSetPLevels ( void *fac_vdata, NALU_HYPRE_Int nparts, NALU_HYPRE_Int *plevels );
NALU_HYPRE_Int hypre_FACSetPRefinements ( void *fac_vdata, NALU_HYPRE_Int nparts, hypre_Index *prefinements);
NALU_HYPRE_Int hypre_FACSetMaxLevels ( void *fac_vdata, NALU_HYPRE_Int nparts );
NALU_HYPRE_Int hypre_FACSetMaxIter ( void *fac_vdata, NALU_HYPRE_Int max_iter );
NALU_HYPRE_Int hypre_FACSetRelChange ( void *fac_vdata, NALU_HYPRE_Int rel_change );
NALU_HYPRE_Int hypre_FACSetZeroGuess ( void *fac_vdata, NALU_HYPRE_Int zero_guess );
NALU_HYPRE_Int hypre_FACSetRelaxType ( void *fac_vdata, NALU_HYPRE_Int relax_type );
NALU_HYPRE_Int hypre_FACSetJacobiWeight ( void *fac_vdata, NALU_HYPRE_Real weight );
NALU_HYPRE_Int hypre_FACSetNumPreSmooth ( void *fac_vdata, NALU_HYPRE_Int num_pre_smooth );
NALU_HYPRE_Int hypre_FACSetNumPostSmooth ( void *fac_vdata, NALU_HYPRE_Int num_post_smooth );
NALU_HYPRE_Int hypre_FACSetCoarseSolverType ( void *fac_vdata, NALU_HYPRE_Int csolver_type );
NALU_HYPRE_Int hypre_FACSetLogging ( void *fac_vdata, NALU_HYPRE_Int logging );
NALU_HYPRE_Int hypre_FACGetNumIterations ( void *fac_vdata, NALU_HYPRE_Int *num_iterations );
NALU_HYPRE_Int hypre_FACPrintLogging ( void *fac_vdata, NALU_HYPRE_Int myid );
NALU_HYPRE_Int hypre_FACGetFinalRelativeResidualNorm ( void *fac_vdata,
                                                  NALU_HYPRE_Real *relative_residual_norm );

/* fac_cf_coarsen.c */
NALU_HYPRE_Int hypre_AMR_CFCoarsen ( hypre_SStructMatrix *A, hypre_SStructMatrix *fac_A,
                                hypre_Index refine_factors, NALU_HYPRE_Int level );

/* fac_CFInterfaceExtents.c */
hypre_BoxArray *hypre_CFInterfaceExtents ( hypre_Box *fgrid_box, hypre_Box *cgrid_box,
                                           hypre_StructStencil *stencils, hypre_Index rfactors );
NALU_HYPRE_Int hypre_CFInterfaceExtents2 ( hypre_Box *fgrid_box, hypre_Box *cgrid_box,
                                      hypre_StructStencil *stencils, hypre_Index rfactors, hypre_BoxArray *cf_interface );

/* fac_cfstencil_box.c */
hypre_Box *hypre_CF_StenBox ( hypre_Box *fgrid_box, hypre_Box *cgrid_box, hypre_Index stencil_shape,
                              hypre_Index rfactors, NALU_HYPRE_Int ndim );

/* fac_interp2.c */
NALU_HYPRE_Int hypre_FacSemiInterpCreate2 ( void **fac_interp_vdata_ptr );
NALU_HYPRE_Int hypre_FacSemiInterpDestroy2 ( void *fac_interp_vdata );
NALU_HYPRE_Int hypre_FacSemiInterpSetup2 ( void *fac_interp_vdata, hypre_SStructVector *e,
                                      hypre_SStructPVector *ec, hypre_Index rfactors );
NALU_HYPRE_Int hypre_FAC_IdentityInterp2 ( void *fac_interp_vdata, hypre_SStructPVector *xc,
                                      hypre_SStructVector *e );
NALU_HYPRE_Int hypre_FAC_WeightedInterp2 ( void *fac_interp_vdata, hypre_SStructPVector *xc,
                                      hypre_SStructVector *e_parts );

/* fac_relax.c */
NALU_HYPRE_Int hypre_FacLocalRelax ( void *relax_vdata, hypre_SStructPMatrix *A, hypre_SStructPVector *x,
                                hypre_SStructPVector *b, NALU_HYPRE_Int num_relax, NALU_HYPRE_Int *zero_guess );

/* fac_restrict2.c */
NALU_HYPRE_Int hypre_FacSemiRestrictCreate2 ( void **fac_restrict_vdata_ptr );
NALU_HYPRE_Int hypre_FacSemiRestrictSetup2 ( void *fac_restrict_vdata, hypre_SStructVector *r,
                                        NALU_HYPRE_Int part_crse, NALU_HYPRE_Int part_fine, hypre_SStructPVector *rc, hypre_Index rfactors );
NALU_HYPRE_Int hypre_FACRestrict2 ( void *fac_restrict_vdata, hypre_SStructVector *xf,
                               hypre_SStructPVector *xc );
NALU_HYPRE_Int hypre_FacSemiRestrictDestroy2 ( void *fac_restrict_vdata );

/* fac_setup2.c */
NALU_HYPRE_Int hypre_FacSetup2 ( void *fac_vdata, hypre_SStructMatrix *A_in, hypre_SStructVector *b,
                            hypre_SStructVector *x );

/* fac_solve3.c */
NALU_HYPRE_Int hypre_FACSolve3 ( void *fac_vdata, hypre_SStructMatrix *A_user, hypre_SStructVector *b_in,
                            hypre_SStructVector *x_in );

/* fac_zero_cdata.c */
NALU_HYPRE_Int hypre_FacZeroCData ( void *fac_vdata, hypre_SStructMatrix *A );

/* fac_zero_stencilcoef.c */
NALU_HYPRE_Int hypre_FacZeroCFSten ( hypre_SStructPMatrix *Af, hypre_SStructPMatrix *Ac,
                                hypre_SStructGrid *grid, NALU_HYPRE_Int fine_part, hypre_Index rfactors );
NALU_HYPRE_Int hypre_FacZeroFCSten ( hypre_SStructPMatrix *A, hypre_SStructGrid *grid,
                                NALU_HYPRE_Int fine_part );

/* bsearch.c */
NALU_HYPRE_Int hypre_LowerBinarySearch ( NALU_HYPRE_Int *list, NALU_HYPRE_Int value, NALU_HYPRE_Int list_length );
NALU_HYPRE_Int hypre_UpperBinarySearch ( NALU_HYPRE_Int *list, NALU_HYPRE_Int value, NALU_HYPRE_Int list_length );

/* maxwell_solve2.c */
NALU_HYPRE_Int hypre_MaxwellSolve2 ( void *maxwell_vdata, hypre_SStructMatrix *A_in,
                                hypre_SStructVector *f, hypre_SStructVector *u );

/* maxwell_solve.c */
NALU_HYPRE_Int hypre_MaxwellSolve ( void *maxwell_vdata, hypre_SStructMatrix *A_in,
                               hypre_SStructVector *f, hypre_SStructVector *u );

/* NALU_HYPRE_sstruct_bicgstab.c */
NALU_HYPRE_Int NALU_HYPRE_SStructBiCGSTABCreate ( MPI_Comm comm, NALU_HYPRE_SStructSolver *solver );
NALU_HYPRE_Int NALU_HYPRE_SStructBiCGSTABDestroy ( NALU_HYPRE_SStructSolver solver );
NALU_HYPRE_Int NALU_HYPRE_SStructBiCGSTABSetup ( NALU_HYPRE_SStructSolver solver, NALU_HYPRE_SStructMatrix A,
                                       NALU_HYPRE_SStructVector b, NALU_HYPRE_SStructVector x );
NALU_HYPRE_Int NALU_HYPRE_SStructBiCGSTABSolve ( NALU_HYPRE_SStructSolver solver, NALU_HYPRE_SStructMatrix A,
                                       NALU_HYPRE_SStructVector b, NALU_HYPRE_SStructVector x );
NALU_HYPRE_Int NALU_HYPRE_SStructBiCGSTABSetTol ( NALU_HYPRE_SStructSolver solver, NALU_HYPRE_Real tol );
NALU_HYPRE_Int NALU_HYPRE_SStructBiCGSTABSetAbsoluteTol ( NALU_HYPRE_SStructSolver solver, NALU_HYPRE_Real tol );
NALU_HYPRE_Int NALU_HYPRE_SStructBiCGSTABSetMinIter ( NALU_HYPRE_SStructSolver solver, NALU_HYPRE_Int min_iter );
NALU_HYPRE_Int NALU_HYPRE_SStructBiCGSTABSetMaxIter ( NALU_HYPRE_SStructSolver solver, NALU_HYPRE_Int max_iter );
NALU_HYPRE_Int NALU_HYPRE_SStructBiCGSTABSetStopCrit ( NALU_HYPRE_SStructSolver solver, NALU_HYPRE_Int stop_crit );
NALU_HYPRE_Int NALU_HYPRE_SStructBiCGSTABSetPrecond ( NALU_HYPRE_SStructSolver solver,
                                            NALU_HYPRE_PtrToSStructSolverFcn precond, NALU_HYPRE_PtrToSStructSolverFcn precond_setup,
                                            void *precond_data );
NALU_HYPRE_Int NALU_HYPRE_SStructBiCGSTABSetLogging ( NALU_HYPRE_SStructSolver solver, NALU_HYPRE_Int logging );
NALU_HYPRE_Int NALU_HYPRE_SStructBiCGSTABSetPrintLevel ( NALU_HYPRE_SStructSolver solver, NALU_HYPRE_Int print_level );
NALU_HYPRE_Int NALU_HYPRE_SStructBiCGSTABGetNumIterations ( NALU_HYPRE_SStructSolver solver,
                                                  NALU_HYPRE_Int *num_iterations );
NALU_HYPRE_Int NALU_HYPRE_SStructBiCGSTABGetFinalRelativeResidualNorm ( NALU_HYPRE_SStructSolver solver,
                                                              NALU_HYPRE_Real *norm );
NALU_HYPRE_Int NALU_HYPRE_SStructBiCGSTABGetResidual ( NALU_HYPRE_SStructSolver solver, void **residual );

/* NALU_HYPRE_sstruct_flexgmres.c */
NALU_HYPRE_Int NALU_HYPRE_SStructFlexGMRESCreate ( MPI_Comm comm, NALU_HYPRE_SStructSolver *solver );
NALU_HYPRE_Int NALU_HYPRE_SStructFlexGMRESDestroy ( NALU_HYPRE_SStructSolver solver );
NALU_HYPRE_Int NALU_HYPRE_SStructFlexGMRESSetup ( NALU_HYPRE_SStructSolver solver, NALU_HYPRE_SStructMatrix A,
                                        NALU_HYPRE_SStructVector b, NALU_HYPRE_SStructVector x );
NALU_HYPRE_Int NALU_HYPRE_SStructFlexGMRESSolve ( NALU_HYPRE_SStructSolver solver, NALU_HYPRE_SStructMatrix A,
                                        NALU_HYPRE_SStructVector b, NALU_HYPRE_SStructVector x );
NALU_HYPRE_Int NALU_HYPRE_SStructFlexGMRESSetKDim ( NALU_HYPRE_SStructSolver solver, NALU_HYPRE_Int k_dim );
NALU_HYPRE_Int NALU_HYPRE_SStructFlexGMRESSetTol ( NALU_HYPRE_SStructSolver solver, NALU_HYPRE_Real tol );
NALU_HYPRE_Int NALU_HYPRE_SStructFlexGMRESSetAbsoluteTol ( NALU_HYPRE_SStructSolver solver, NALU_HYPRE_Real tol );
NALU_HYPRE_Int NALU_HYPRE_SStructFlexGMRESSetMinIter ( NALU_HYPRE_SStructSolver solver, NALU_HYPRE_Int min_iter );
NALU_HYPRE_Int NALU_HYPRE_SStructFlexGMRESSetMaxIter ( NALU_HYPRE_SStructSolver solver, NALU_HYPRE_Int max_iter );
NALU_HYPRE_Int NALU_HYPRE_SStructFlexGMRESSetPrecond ( NALU_HYPRE_SStructSolver solver,
                                             NALU_HYPRE_PtrToSStructSolverFcn precond, NALU_HYPRE_PtrToSStructSolverFcn precond_setup,
                                             void *precond_data );
NALU_HYPRE_Int NALU_HYPRE_SStructFlexGMRESSetLogging ( NALU_HYPRE_SStructSolver solver, NALU_HYPRE_Int logging );
NALU_HYPRE_Int NALU_HYPRE_SStructFlexGMRESSetPrintLevel ( NALU_HYPRE_SStructSolver solver, NALU_HYPRE_Int level );
NALU_HYPRE_Int NALU_HYPRE_SStructFlexGMRESGetNumIterations ( NALU_HYPRE_SStructSolver solver,
                                                   NALU_HYPRE_Int *num_iterations );
NALU_HYPRE_Int NALU_HYPRE_SStructFlexGMRESGetFinalRelativeResidualNorm ( NALU_HYPRE_SStructSolver solver,
                                                               NALU_HYPRE_Real *norm );
NALU_HYPRE_Int NALU_HYPRE_SStructFlexGMRESGetResidual ( NALU_HYPRE_SStructSolver solver, void **residual );
NALU_HYPRE_Int NALU_HYPRE_SStructFlexGMRESSetModifyPC ( NALU_HYPRE_SStructSolver solver,
                                              NALU_HYPRE_PtrToModifyPCFcn modify_pc );

/* NALU_HYPRE_sstruct_gmres.c */
NALU_HYPRE_Int NALU_HYPRE_SStructGMRESCreate ( MPI_Comm comm, NALU_HYPRE_SStructSolver *solver );
NALU_HYPRE_Int NALU_HYPRE_SStructGMRESDestroy ( NALU_HYPRE_SStructSolver solver );
NALU_HYPRE_Int NALU_HYPRE_SStructGMRESSetup ( NALU_HYPRE_SStructSolver solver, NALU_HYPRE_SStructMatrix A,
                                    NALU_HYPRE_SStructVector b, NALU_HYPRE_SStructVector x );
NALU_HYPRE_Int NALU_HYPRE_SStructGMRESSolve ( NALU_HYPRE_SStructSolver solver, NALU_HYPRE_SStructMatrix A,
                                    NALU_HYPRE_SStructVector b, NALU_HYPRE_SStructVector x );
NALU_HYPRE_Int NALU_HYPRE_SStructGMRESSetKDim ( NALU_HYPRE_SStructSolver solver, NALU_HYPRE_Int k_dim );
NALU_HYPRE_Int NALU_HYPRE_SStructGMRESSetTol ( NALU_HYPRE_SStructSolver solver, NALU_HYPRE_Real tol );
NALU_HYPRE_Int NALU_HYPRE_SStructGMRESSetAbsoluteTol ( NALU_HYPRE_SStructSolver solver, NALU_HYPRE_Real atol );
NALU_HYPRE_Int NALU_HYPRE_SStructGMRESSetMinIter ( NALU_HYPRE_SStructSolver solver, NALU_HYPRE_Int min_iter );
NALU_HYPRE_Int NALU_HYPRE_SStructGMRESSetMaxIter ( NALU_HYPRE_SStructSolver solver, NALU_HYPRE_Int max_iter );
NALU_HYPRE_Int NALU_HYPRE_SStructGMRESSetStopCrit ( NALU_HYPRE_SStructSolver solver, NALU_HYPRE_Int stop_crit );
NALU_HYPRE_Int NALU_HYPRE_SStructGMRESSetPrecond ( NALU_HYPRE_SStructSolver solver,
                                         NALU_HYPRE_PtrToSStructSolverFcn precond, NALU_HYPRE_PtrToSStructSolverFcn precond_setup,
                                         void *precond_data );
NALU_HYPRE_Int NALU_HYPRE_SStructGMRESSetLogging ( NALU_HYPRE_SStructSolver solver, NALU_HYPRE_Int logging );
NALU_HYPRE_Int NALU_HYPRE_SStructGMRESSetPrintLevel ( NALU_HYPRE_SStructSolver solver, NALU_HYPRE_Int level );
NALU_HYPRE_Int NALU_HYPRE_SStructGMRESGetNumIterations ( NALU_HYPRE_SStructSolver solver,
                                               NALU_HYPRE_Int *num_iterations );
NALU_HYPRE_Int NALU_HYPRE_SStructGMRESGetFinalRelativeResidualNorm ( NALU_HYPRE_SStructSolver solver,
                                                           NALU_HYPRE_Real *norm );
NALU_HYPRE_Int NALU_HYPRE_SStructGMRESGetResidual ( NALU_HYPRE_SStructSolver solver, void **residual );

/* NALU_HYPRE_sstruct_int.c */
NALU_HYPRE_Int hypre_SStructPVectorSetRandomValues ( hypre_SStructPVector *pvector, NALU_HYPRE_Int seed );
NALU_HYPRE_Int hypre_SStructVectorSetRandomValues ( hypre_SStructVector *vector, NALU_HYPRE_Int seed );
NALU_HYPRE_Int hypre_SStructSetRandomValues ( void *v, NALU_HYPRE_Int seed );
NALU_HYPRE_Int NALU_HYPRE_SStructSetupInterpreter ( mv_InterfaceInterpreter *i );
NALU_HYPRE_Int NALU_HYPRE_SStructSetupMatvec ( NALU_HYPRE_MatvecFunctions *mv );

/* NALU_HYPRE_sstruct_InterFAC.c */
NALU_HYPRE_Int NALU_HYPRE_SStructFACCreate ( MPI_Comm comm, NALU_HYPRE_SStructSolver *solver );
NALU_HYPRE_Int NALU_HYPRE_SStructFACDestroy2 ( NALU_HYPRE_SStructSolver solver );
NALU_HYPRE_Int NALU_HYPRE_SStructFACAMR_RAP ( NALU_HYPRE_SStructMatrix A, NALU_HYPRE_Int (*rfactors )[NALU_HYPRE_MAXDIM],
                                    NALU_HYPRE_SStructMatrix *fac_A );
NALU_HYPRE_Int NALU_HYPRE_SStructFACSetup2 ( NALU_HYPRE_SStructSolver solver, NALU_HYPRE_SStructMatrix A,
                                   NALU_HYPRE_SStructVector b, NALU_HYPRE_SStructVector x );
NALU_HYPRE_Int NALU_HYPRE_SStructFACSolve3 ( NALU_HYPRE_SStructSolver solver, NALU_HYPRE_SStructMatrix A,
                                   NALU_HYPRE_SStructVector b, NALU_HYPRE_SStructVector x );
NALU_HYPRE_Int NALU_HYPRE_SStructFACSetTol ( NALU_HYPRE_SStructSolver solver, NALU_HYPRE_Real tol );
NALU_HYPRE_Int NALU_HYPRE_SStructFACSetPLevels ( NALU_HYPRE_SStructSolver solver, NALU_HYPRE_Int nparts,
                                       NALU_HYPRE_Int *plevels );
NALU_HYPRE_Int NALU_HYPRE_SStructFACZeroCFSten ( NALU_HYPRE_SStructMatrix A, NALU_HYPRE_SStructGrid grid,
                                       NALU_HYPRE_Int part, NALU_HYPRE_Int rfactors [NALU_HYPRE_MAXDIM]);
NALU_HYPRE_Int NALU_HYPRE_SStructFACZeroFCSten ( NALU_HYPRE_SStructMatrix A, NALU_HYPRE_SStructGrid grid,
                                       NALU_HYPRE_Int part );
NALU_HYPRE_Int NALU_HYPRE_SStructFACZeroAMRMatrixData ( NALU_HYPRE_SStructMatrix A, NALU_HYPRE_Int part_crse,
                                              NALU_HYPRE_Int rfactors [NALU_HYPRE_MAXDIM]);
NALU_HYPRE_Int NALU_HYPRE_SStructFACZeroAMRVectorData ( NALU_HYPRE_SStructVector b, NALU_HYPRE_Int *plevels,
                                              NALU_HYPRE_Int (*rfactors )[NALU_HYPRE_MAXDIM]);
NALU_HYPRE_Int NALU_HYPRE_SStructFACSetPRefinements ( NALU_HYPRE_SStructSolver solver, NALU_HYPRE_Int nparts,
                                            NALU_HYPRE_Int (*rfactors )[NALU_HYPRE_MAXDIM]);
NALU_HYPRE_Int NALU_HYPRE_SStructFACSetMaxLevels ( NALU_HYPRE_SStructSolver solver, NALU_HYPRE_Int max_levels );
NALU_HYPRE_Int NALU_HYPRE_SStructFACSetMaxIter ( NALU_HYPRE_SStructSolver solver, NALU_HYPRE_Int max_iter );
NALU_HYPRE_Int NALU_HYPRE_SStructFACSetRelChange ( NALU_HYPRE_SStructSolver solver, NALU_HYPRE_Int rel_change );
NALU_HYPRE_Int NALU_HYPRE_SStructFACSetZeroGuess ( NALU_HYPRE_SStructSolver solver );
NALU_HYPRE_Int NALU_HYPRE_SStructFACSetNonZeroGuess ( NALU_HYPRE_SStructSolver solver );
NALU_HYPRE_Int NALU_HYPRE_SStructFACSetRelaxType ( NALU_HYPRE_SStructSolver solver, NALU_HYPRE_Int relax_type );
NALU_HYPRE_Int NALU_HYPRE_SStructFACSetJacobiWeight ( NALU_HYPRE_SStructSolver solver, NALU_HYPRE_Real weight );
NALU_HYPRE_Int NALU_HYPRE_SStructFACSetNumPreRelax ( NALU_HYPRE_SStructSolver solver, NALU_HYPRE_Int num_pre_relax );
NALU_HYPRE_Int NALU_HYPRE_SStructFACSetNumPostRelax ( NALU_HYPRE_SStructSolver solver, NALU_HYPRE_Int num_post_relax );
NALU_HYPRE_Int NALU_HYPRE_SStructFACSetCoarseSolverType ( NALU_HYPRE_SStructSolver solver,
                                                NALU_HYPRE_Int csolver_type );
NALU_HYPRE_Int NALU_HYPRE_SStructFACSetLogging ( NALU_HYPRE_SStructSolver solver, NALU_HYPRE_Int logging );
NALU_HYPRE_Int NALU_HYPRE_SStructFACGetNumIterations ( NALU_HYPRE_SStructSolver solver,
                                             NALU_HYPRE_Int *num_iterations );
NALU_HYPRE_Int NALU_HYPRE_SStructFACGetFinalRelativeResidualNorm ( NALU_HYPRE_SStructSolver solver,
                                                         NALU_HYPRE_Real *norm );

/* NALU_HYPRE_sstruct_lgmres.c */
NALU_HYPRE_Int NALU_HYPRE_SStructLGMRESCreate ( MPI_Comm comm, NALU_HYPRE_SStructSolver *solver );
NALU_HYPRE_Int NALU_HYPRE_SStructLGMRESDestroy ( NALU_HYPRE_SStructSolver solver );
NALU_HYPRE_Int NALU_HYPRE_SStructLGMRESSetup ( NALU_HYPRE_SStructSolver solver, NALU_HYPRE_SStructMatrix A,
                                     NALU_HYPRE_SStructVector b, NALU_HYPRE_SStructVector x );
NALU_HYPRE_Int NALU_HYPRE_SStructLGMRESSolve ( NALU_HYPRE_SStructSolver solver, NALU_HYPRE_SStructMatrix A,
                                     NALU_HYPRE_SStructVector b, NALU_HYPRE_SStructVector x );
NALU_HYPRE_Int NALU_HYPRE_SStructLGMRESSetKDim ( NALU_HYPRE_SStructSolver solver, NALU_HYPRE_Int k_dim );
NALU_HYPRE_Int NALU_HYPRE_SStructLGMRESSetAugDim ( NALU_HYPRE_SStructSolver solver, NALU_HYPRE_Int aug_dim );
NALU_HYPRE_Int NALU_HYPRE_SStructLGMRESSetTol ( NALU_HYPRE_SStructSolver solver, NALU_HYPRE_Real tol );
NALU_HYPRE_Int NALU_HYPRE_SStructLGMRESSetAbsoluteTol ( NALU_HYPRE_SStructSolver solver, NALU_HYPRE_Real atol );
NALU_HYPRE_Int NALU_HYPRE_SStructLGMRESSetMinIter ( NALU_HYPRE_SStructSolver solver, NALU_HYPRE_Int min_iter );
NALU_HYPRE_Int NALU_HYPRE_SStructLGMRESSetMaxIter ( NALU_HYPRE_SStructSolver solver, NALU_HYPRE_Int max_iter );
NALU_HYPRE_Int NALU_HYPRE_SStructLGMRESSetPrecond ( NALU_HYPRE_SStructSolver solver,
                                          NALU_HYPRE_PtrToSStructSolverFcn precond, NALU_HYPRE_PtrToSStructSolverFcn precond_setup,
                                          void *precond_data );
NALU_HYPRE_Int NALU_HYPRE_SStructLGMRESSetLogging ( NALU_HYPRE_SStructSolver solver, NALU_HYPRE_Int logging );
NALU_HYPRE_Int NALU_HYPRE_SStructLGMRESSetPrintLevel ( NALU_HYPRE_SStructSolver solver, NALU_HYPRE_Int level );
NALU_HYPRE_Int NALU_HYPRE_SStructLGMRESGetNumIterations ( NALU_HYPRE_SStructSolver solver,
                                                NALU_HYPRE_Int *num_iterations );
NALU_HYPRE_Int NALU_HYPRE_SStructLGMRESGetFinalRelativeResidualNorm ( NALU_HYPRE_SStructSolver solver,
                                                            NALU_HYPRE_Real *norm );
NALU_HYPRE_Int NALU_HYPRE_SStructLGMRESGetResidual ( NALU_HYPRE_SStructSolver solver, void **residual );

/* NALU_HYPRE_sstruct_maxwell.c */
NALU_HYPRE_Int NALU_HYPRE_SStructMaxwellCreate ( MPI_Comm comm, NALU_HYPRE_SStructSolver *solver );
NALU_HYPRE_Int NALU_HYPRE_SStructMaxwellDestroy ( NALU_HYPRE_SStructSolver solver );
NALU_HYPRE_Int NALU_HYPRE_SStructMaxwellSetup ( NALU_HYPRE_SStructSolver solver, NALU_HYPRE_SStructMatrix A,
                                      NALU_HYPRE_SStructVector b, NALU_HYPRE_SStructVector x );
NALU_HYPRE_Int NALU_HYPRE_SStructMaxwellSolve ( NALU_HYPRE_SStructSolver solver, NALU_HYPRE_SStructMatrix A,
                                      NALU_HYPRE_SStructVector b, NALU_HYPRE_SStructVector x );
NALU_HYPRE_Int NALU_HYPRE_SStructMaxwellSolve2 ( NALU_HYPRE_SStructSolver solver, NALU_HYPRE_SStructMatrix A,
                                       NALU_HYPRE_SStructVector b, NALU_HYPRE_SStructVector x );
NALU_HYPRE_Int NALU_HYPRE_MaxwellGrad ( NALU_HYPRE_SStructGrid grid, NALU_HYPRE_ParCSRMatrix *T );
NALU_HYPRE_Int NALU_HYPRE_SStructMaxwellSetGrad ( NALU_HYPRE_SStructSolver solver, NALU_HYPRE_ParCSRMatrix T );
NALU_HYPRE_Int NALU_HYPRE_SStructMaxwellSetRfactors ( NALU_HYPRE_SStructSolver solver,
                                            NALU_HYPRE_Int rfactors [NALU_HYPRE_MAXDIM]);
NALU_HYPRE_Int NALU_HYPRE_SStructMaxwellSetTol ( NALU_HYPRE_SStructSolver solver, NALU_HYPRE_Real tol );
NALU_HYPRE_Int NALU_HYPRE_SStructMaxwellSetConstantCoef ( NALU_HYPRE_SStructSolver solver,
                                                NALU_HYPRE_Int constant_coef );
NALU_HYPRE_Int NALU_HYPRE_SStructMaxwellSetMaxIter ( NALU_HYPRE_SStructSolver solver, NALU_HYPRE_Int max_iter );
NALU_HYPRE_Int NALU_HYPRE_SStructMaxwellSetRelChange ( NALU_HYPRE_SStructSolver solver, NALU_HYPRE_Int rel_change );
NALU_HYPRE_Int NALU_HYPRE_SStructMaxwellSetNumPreRelax ( NALU_HYPRE_SStructSolver solver,
                                               NALU_HYPRE_Int num_pre_relax );
NALU_HYPRE_Int NALU_HYPRE_SStructMaxwellSetNumPostRelax ( NALU_HYPRE_SStructSolver solver,
                                                NALU_HYPRE_Int num_post_relax );
NALU_HYPRE_Int NALU_HYPRE_SStructMaxwellSetLogging ( NALU_HYPRE_SStructSolver solver, NALU_HYPRE_Int logging );
NALU_HYPRE_Int NALU_HYPRE_SStructMaxwellSetPrintLevel ( NALU_HYPRE_SStructSolver solver, NALU_HYPRE_Int print_level );
NALU_HYPRE_Int NALU_HYPRE_SStructMaxwellPrintLogging ( NALU_HYPRE_SStructSolver solver, NALU_HYPRE_Int myid );
NALU_HYPRE_Int NALU_HYPRE_SStructMaxwellGetNumIterations ( NALU_HYPRE_SStructSolver solver,
                                                 NALU_HYPRE_Int *num_iterations );
NALU_HYPRE_Int NALU_HYPRE_SStructMaxwellGetFinalRelativeResidualNorm ( NALU_HYPRE_SStructSolver solver,
                                                             NALU_HYPRE_Real *norm );
NALU_HYPRE_Int NALU_HYPRE_SStructMaxwellPhysBdy ( NALU_HYPRE_SStructGrid *grid_l, NALU_HYPRE_Int num_levels,
                                        NALU_HYPRE_Int rfactors [NALU_HYPRE_MAXDIM], NALU_HYPRE_Int ***BdryRanks_ptr, NALU_HYPRE_Int **BdryRanksCnt_ptr );
NALU_HYPRE_Int NALU_HYPRE_SStructMaxwellEliminateRowsCols ( NALU_HYPRE_ParCSRMatrix parA, NALU_HYPRE_Int nrows,
                                                  NALU_HYPRE_Int *rows );
NALU_HYPRE_Int NALU_HYPRE_SStructMaxwellZeroVector ( NALU_HYPRE_ParVector v, NALU_HYPRE_Int *rows, NALU_HYPRE_Int nrows );

/* NALU_HYPRE_sstruct_pcg.c */
NALU_HYPRE_Int NALU_HYPRE_SStructPCGCreate ( MPI_Comm comm, NALU_HYPRE_SStructSolver *solver );
NALU_HYPRE_Int NALU_HYPRE_SStructPCGDestroy ( NALU_HYPRE_SStructSolver solver );
NALU_HYPRE_Int NALU_HYPRE_SStructPCGSetup ( NALU_HYPRE_SStructSolver solver, NALU_HYPRE_SStructMatrix A,
                                  NALU_HYPRE_SStructVector b, NALU_HYPRE_SStructVector x );
NALU_HYPRE_Int NALU_HYPRE_SStructPCGSolve ( NALU_HYPRE_SStructSolver solver, NALU_HYPRE_SStructMatrix A,
                                  NALU_HYPRE_SStructVector b, NALU_HYPRE_SStructVector x );
NALU_HYPRE_Int NALU_HYPRE_SStructPCGSetTol ( NALU_HYPRE_SStructSolver solver, NALU_HYPRE_Real tol );
NALU_HYPRE_Int NALU_HYPRE_SStructPCGSetAbsoluteTol ( NALU_HYPRE_SStructSolver solver, NALU_HYPRE_Real tol );
NALU_HYPRE_Int NALU_HYPRE_SStructPCGSetMaxIter ( NALU_HYPRE_SStructSolver solver, NALU_HYPRE_Int max_iter );
NALU_HYPRE_Int NALU_HYPRE_SStructPCGSetTwoNorm ( NALU_HYPRE_SStructSolver solver, NALU_HYPRE_Int two_norm );
NALU_HYPRE_Int NALU_HYPRE_SStructPCGSetRelChange ( NALU_HYPRE_SStructSolver solver, NALU_HYPRE_Int rel_change );
NALU_HYPRE_Int NALU_HYPRE_SStructPCGSetPrecond ( NALU_HYPRE_SStructSolver solver,
                                       NALU_HYPRE_PtrToSStructSolverFcn precond, NALU_HYPRE_PtrToSStructSolverFcn precond_setup,
                                       void *precond_data );
NALU_HYPRE_Int NALU_HYPRE_SStructPCGSetLogging ( NALU_HYPRE_SStructSolver solver, NALU_HYPRE_Int logging );
NALU_HYPRE_Int NALU_HYPRE_SStructPCGSetPrintLevel ( NALU_HYPRE_SStructSolver solver, NALU_HYPRE_Int level );
NALU_HYPRE_Int NALU_HYPRE_SStructPCGGetNumIterations ( NALU_HYPRE_SStructSolver solver,
                                             NALU_HYPRE_Int *num_iterations );
NALU_HYPRE_Int NALU_HYPRE_SStructPCGGetFinalRelativeResidualNorm ( NALU_HYPRE_SStructSolver solver,
                                                         NALU_HYPRE_Real *norm );
NALU_HYPRE_Int NALU_HYPRE_SStructPCGGetResidual ( NALU_HYPRE_SStructSolver solver, void **residual );
NALU_HYPRE_Int NALU_HYPRE_SStructDiagScaleSetup ( NALU_HYPRE_SStructSolver solver, NALU_HYPRE_SStructMatrix A,
                                        NALU_HYPRE_SStructVector y, NALU_HYPRE_SStructVector x );
NALU_HYPRE_Int NALU_HYPRE_SStructDiagScale ( NALU_HYPRE_SStructSolver solver, NALU_HYPRE_SStructMatrix A,
                                   NALU_HYPRE_SStructVector y, NALU_HYPRE_SStructVector x );

/* NALU_HYPRE_sstruct_split.c */
NALU_HYPRE_Int NALU_HYPRE_SStructSplitCreate ( MPI_Comm comm, NALU_HYPRE_SStructSolver *solver_ptr );
NALU_HYPRE_Int NALU_HYPRE_SStructSplitDestroy ( NALU_HYPRE_SStructSolver solver );
NALU_HYPRE_Int NALU_HYPRE_SStructSplitSetup ( NALU_HYPRE_SStructSolver solver, NALU_HYPRE_SStructMatrix A,
                                    NALU_HYPRE_SStructVector b, NALU_HYPRE_SStructVector x );
NALU_HYPRE_Int NALU_HYPRE_SStructSplitSolve ( NALU_HYPRE_SStructSolver solver, NALU_HYPRE_SStructMatrix A,
                                    NALU_HYPRE_SStructVector b, NALU_HYPRE_SStructVector x );
NALU_HYPRE_Int NALU_HYPRE_SStructSplitSetTol ( NALU_HYPRE_SStructSolver solver, NALU_HYPRE_Real tol );
NALU_HYPRE_Int NALU_HYPRE_SStructSplitSetMaxIter ( NALU_HYPRE_SStructSolver solver, NALU_HYPRE_Int max_iter );
NALU_HYPRE_Int NALU_HYPRE_SStructSplitSetZeroGuess ( NALU_HYPRE_SStructSolver solver );
NALU_HYPRE_Int NALU_HYPRE_SStructSplitSetNonZeroGuess ( NALU_HYPRE_SStructSolver solver );
NALU_HYPRE_Int NALU_HYPRE_SStructSplitSetStructSolver ( NALU_HYPRE_SStructSolver solver, NALU_HYPRE_Int ssolver );
NALU_HYPRE_Int NALU_HYPRE_SStructSplitGetNumIterations ( NALU_HYPRE_SStructSolver solver,
                                               NALU_HYPRE_Int *num_iterations );
NALU_HYPRE_Int NALU_HYPRE_SStructSplitGetFinalRelativeResidualNorm ( NALU_HYPRE_SStructSolver solver,
                                                           NALU_HYPRE_Real *norm );

/* NALU_HYPRE_sstruct_sys_pfmg.c */
NALU_HYPRE_Int NALU_HYPRE_SStructSysPFMGCreate ( MPI_Comm comm, NALU_HYPRE_SStructSolver *solver );
NALU_HYPRE_Int NALU_HYPRE_SStructSysPFMGDestroy ( NALU_HYPRE_SStructSolver solver );
NALU_HYPRE_Int NALU_HYPRE_SStructSysPFMGSetup ( NALU_HYPRE_SStructSolver solver, NALU_HYPRE_SStructMatrix A,
                                      NALU_HYPRE_SStructVector b, NALU_HYPRE_SStructVector x );
NALU_HYPRE_Int NALU_HYPRE_SStructSysPFMGSolve ( NALU_HYPRE_SStructSolver solver, NALU_HYPRE_SStructMatrix A,
                                      NALU_HYPRE_SStructVector b, NALU_HYPRE_SStructVector x );
NALU_HYPRE_Int NALU_HYPRE_SStructSysPFMGSetTol ( NALU_HYPRE_SStructSolver solver, NALU_HYPRE_Real tol );
NALU_HYPRE_Int NALU_HYPRE_SStructSysPFMGSetMaxIter ( NALU_HYPRE_SStructSolver solver, NALU_HYPRE_Int max_iter );
NALU_HYPRE_Int NALU_HYPRE_SStructSysPFMGSetRelChange ( NALU_HYPRE_SStructSolver solver, NALU_HYPRE_Int rel_change );
NALU_HYPRE_Int NALU_HYPRE_SStructSysPFMGSetZeroGuess ( NALU_HYPRE_SStructSolver solver );
NALU_HYPRE_Int NALU_HYPRE_SStructSysPFMGSetNonZeroGuess ( NALU_HYPRE_SStructSolver solver );
NALU_HYPRE_Int NALU_HYPRE_SStructSysPFMGSetRelaxType ( NALU_HYPRE_SStructSolver solver, NALU_HYPRE_Int relax_type );
NALU_HYPRE_Int NALU_HYPRE_SStructSysPFMGSetJacobiWeight ( NALU_HYPRE_SStructSolver solver, NALU_HYPRE_Real weight );
NALU_HYPRE_Int NALU_HYPRE_SStructSysPFMGSetNumPreRelax ( NALU_HYPRE_SStructSolver solver,
                                               NALU_HYPRE_Int num_pre_relax );
NALU_HYPRE_Int NALU_HYPRE_SStructSysPFMGSetNumPostRelax ( NALU_HYPRE_SStructSolver solver,
                                                NALU_HYPRE_Int num_post_relax );
NALU_HYPRE_Int NALU_HYPRE_SStructSysPFMGSetSkipRelax ( NALU_HYPRE_SStructSolver solver, NALU_HYPRE_Int skip_relax );
NALU_HYPRE_Int NALU_HYPRE_SStructSysPFMGSetDxyz ( NALU_HYPRE_SStructSolver solver, NALU_HYPRE_Real *dxyz );
NALU_HYPRE_Int NALU_HYPRE_SStructSysPFMGSetLogging ( NALU_HYPRE_SStructSolver solver, NALU_HYPRE_Int logging );
NALU_HYPRE_Int NALU_HYPRE_SStructSysPFMGSetPrintLevel ( NALU_HYPRE_SStructSolver solver, NALU_HYPRE_Int print_level );
NALU_HYPRE_Int NALU_HYPRE_SStructSysPFMGGetNumIterations ( NALU_HYPRE_SStructSolver solver,
                                                 NALU_HYPRE_Int *num_iterations );
NALU_HYPRE_Int NALU_HYPRE_SStructSysPFMGGetFinalRelativeResidualNorm ( NALU_HYPRE_SStructSolver solver,
                                                             NALU_HYPRE_Real *norm );

/* krylov.c */
NALU_HYPRE_Int hypre_SStructKrylovIdentitySetup ( void *vdata, void *A, void *b, void *x );
NALU_HYPRE_Int hypre_SStructKrylovIdentity ( void *vdata, void *A, void *b, void *x );

/* krylov_sstruct.c */
void *hypre_SStructKrylovCAlloc ( size_t count, size_t elt_size, NALU_HYPRE_MemoryLocation location );
NALU_HYPRE_Int hypre_SStructKrylovFree ( void *ptr );
void *hypre_SStructKrylovCreateVector ( void *vvector );
void *hypre_SStructKrylovCreateVectorArray ( NALU_HYPRE_Int n, void *vvector );
NALU_HYPRE_Int hypre_SStructKrylovDestroyVector ( void *vvector );
void *hypre_SStructKrylovMatvecCreate ( void *A, void *x );
NALU_HYPRE_Int hypre_SStructKrylovMatvec ( void *matvec_data, NALU_HYPRE_Complex alpha, void *A, void *x,
                                      NALU_HYPRE_Complex beta, void *y );
NALU_HYPRE_Int hypre_SStructKrylovMatvecDestroy ( void *matvec_data );
NALU_HYPRE_Real hypre_SStructKrylovInnerProd ( void *x, void *y );
NALU_HYPRE_Int hypre_SStructKrylovCopyVector ( void *x, void *y );
NALU_HYPRE_Int hypre_SStructKrylovClearVector ( void *x );
NALU_HYPRE_Int hypre_SStructKrylovScaleVector ( NALU_HYPRE_Complex alpha, void *x );
NALU_HYPRE_Int hypre_SStructKrylovAxpy ( NALU_HYPRE_Complex alpha, void *x, void *y );
NALU_HYPRE_Int hypre_SStructKrylovCommInfo ( void *A, NALU_HYPRE_Int *my_id, NALU_HYPRE_Int *num_procs );

/* maxwell_grad.c */
hypre_ParCSRMatrix *hypre_Maxwell_Grad ( hypre_SStructGrid *grid );

/* maxwell_physbdy.c */
NALU_HYPRE_Int hypre_Maxwell_PhysBdy ( hypre_SStructGrid **grid_l, NALU_HYPRE_Int num_levels,
                                  hypre_Index rfactors, NALU_HYPRE_Int ***BdryRanksl_ptr, NALU_HYPRE_Int **BdryRanksCntsl_ptr );
NALU_HYPRE_Int hypre_Maxwell_VarBdy ( hypre_SStructPGrid *pgrid, hypre_BoxArrayArray **bdry );

/* maxwell_PNedelec_bdy.c */
NALU_HYPRE_Int hypre_Maxwell_PNedelec_Bdy ( hypre_StructGrid *cell_grid, hypre_SStructPGrid *pgrid,
                                       hypre_BoxArrayArray ****bdry_ptr );

/* maxwell_PNedelec.c */
hypre_IJMatrix *hypre_Maxwell_PNedelec ( hypre_SStructGrid *fgrid_edge,
                                         hypre_SStructGrid *cgrid_edge, hypre_Index rfactor );

/* maxwell_semi_interp.c */
NALU_HYPRE_Int hypre_CreatePTopology ( void **PTopology_vdata_ptr );
NALU_HYPRE_Int hypre_DestroyPTopology ( void *PTopology_vdata );
hypre_IJMatrix *hypre_Maxwell_PTopology ( hypre_SStructGrid *fgrid_edge,
                                          hypre_SStructGrid *cgrid_edge, hypre_SStructGrid *fgrid_face, hypre_SStructGrid *cgrid_face,
                                          hypre_SStructGrid *fgrid_element, hypre_SStructGrid *cgrid_element, hypre_ParCSRMatrix *Aee,
                                          hypre_Index rfactor, void *PTopology_vdata );
NALU_HYPRE_Int hypre_CollapseStencilToStencil ( hypre_ParCSRMatrix *Aee, hypre_SStructGrid *grid,
                                           NALU_HYPRE_Int part, NALU_HYPRE_Int var, hypre_Index pt_location, NALU_HYPRE_Int collapse_dir,
                                           NALU_HYPRE_Int new_stencil_dir, NALU_HYPRE_Real **collapsed_vals_ptr );
NALU_HYPRE_Int hypre_TriDiagSolve ( NALU_HYPRE_Real *diag, NALU_HYPRE_Real *upper, NALU_HYPRE_Real *lower,
                               NALU_HYPRE_Real *rhs, NALU_HYPRE_Int size );

/* maxwell_TV.c */
void *hypre_MaxwellTVCreate ( MPI_Comm comm );
NALU_HYPRE_Int hypre_MaxwellTVDestroy ( void *maxwell_vdata );
NALU_HYPRE_Int hypre_MaxwellSetRfactors ( void *maxwell_vdata, NALU_HYPRE_Int rfactor [NALU_HYPRE_MAXDIM]);
NALU_HYPRE_Int hypre_MaxwellSetGrad ( void *maxwell_vdata, hypre_ParCSRMatrix *T );
NALU_HYPRE_Int hypre_MaxwellSetConstantCoef ( void *maxwell_vdata, NALU_HYPRE_Int constant_coef );
NALU_HYPRE_Int hypre_MaxwellSetTol ( void *maxwell_vdata, NALU_HYPRE_Real tol );
NALU_HYPRE_Int hypre_MaxwellSetMaxIter ( void *maxwell_vdata, NALU_HYPRE_Int max_iter );
NALU_HYPRE_Int hypre_MaxwellSetRelChange ( void *maxwell_vdata, NALU_HYPRE_Int rel_change );
NALU_HYPRE_Int hypre_MaxwellSetNumPreRelax ( void *maxwell_vdata, NALU_HYPRE_Int num_pre_relax );
NALU_HYPRE_Int hypre_MaxwellSetNumPostRelax ( void *maxwell_vdata, NALU_HYPRE_Int num_post_relax );
NALU_HYPRE_Int hypre_MaxwellGetNumIterations ( void *maxwell_vdata, NALU_HYPRE_Int *num_iterations );
NALU_HYPRE_Int hypre_MaxwellSetPrintLevel ( void *maxwell_vdata, NALU_HYPRE_Int print_level );
NALU_HYPRE_Int hypre_MaxwellSetLogging ( void *maxwell_vdata, NALU_HYPRE_Int logging );
NALU_HYPRE_Int hypre_MaxwellPrintLogging ( void *maxwell_vdata, NALU_HYPRE_Int myid );
NALU_HYPRE_Int hypre_MaxwellGetFinalRelativeResidualNorm ( void *maxwell_vdata,
                                                      NALU_HYPRE_Real *relative_residual_norm );

/* maxwell_TV_setup.c */
NALU_HYPRE_Int hypre_MaxwellTV_Setup ( void *maxwell_vdata, hypre_SStructMatrix *Aee_in,
                                  hypre_SStructVector *b_in, hypre_SStructVector *x_in );
NALU_HYPRE_Int hypre_CoarsenPGrid ( hypre_SStructGrid *fgrid, hypre_Index index, hypre_Index stride,
                               NALU_HYPRE_Int part, hypre_SStructGrid *cgrid, NALU_HYPRE_Int *nboxes );
hypre_Box *hypre_BoxContraction ( hypre_Box *box, hypre_StructGrid *sgrid, hypre_Index rfactor );

/* maxwell_zeroBC.c */
NALU_HYPRE_Int hypre_ParVectorZeroBCValues ( hypre_ParVector *v, NALU_HYPRE_Int *rows, NALU_HYPRE_Int nrows );
NALU_HYPRE_Int hypre_SeqVectorZeroBCValues ( hypre_Vector *v, NALU_HYPRE_Int *rows, NALU_HYPRE_Int nrows );

/* nd1_amge_interpolation.c */
NALU_HYPRE_Int hypre_ND1AMGeInterpolation ( hypre_ParCSRMatrix *Aee, hypre_ParCSRMatrix *ELEM_idof,
                                       hypre_ParCSRMatrix *FACE_idof, hypre_ParCSRMatrix *EDGE_idof, hypre_ParCSRMatrix *ELEM_FACE,
                                       hypre_ParCSRMatrix *ELEM_EDGE, NALU_HYPRE_Int num_OffProcRows, hypre_MaxwellOffProcRow **OffProcRows,
                                       hypre_IJMatrix *IJ_dof_DOF );
NALU_HYPRE_Int hypre_HarmonicExtension ( hypre_CSRMatrix *A, hypre_CSRMatrix *P, NALU_HYPRE_Int num_DOF,
                                    NALU_HYPRE_BigInt *DOF, NALU_HYPRE_Int num_idof, NALU_HYPRE_BigInt *idof, NALU_HYPRE_Int num_bdof, NALU_HYPRE_BigInt *bdof );

/* node_relax.c */
void *hypre_NodeRelaxCreate ( MPI_Comm comm );
NALU_HYPRE_Int hypre_NodeRelaxDestroy ( void *relax_vdata );
NALU_HYPRE_Int hypre_NodeRelaxSetup ( void *relax_vdata, hypre_SStructPMatrix *A,
                                 hypre_SStructPVector *b, hypre_SStructPVector *x );
NALU_HYPRE_Int hypre_NodeRelax ( void *relax_vdata, hypre_SStructPMatrix *A, hypre_SStructPVector *b,
                            hypre_SStructPVector *x );
NALU_HYPRE_Int hypre_NodeRelaxSetTol ( void *relax_vdata, NALU_HYPRE_Real tol );
NALU_HYPRE_Int hypre_NodeRelaxSetMaxIter ( void *relax_vdata, NALU_HYPRE_Int max_iter );
NALU_HYPRE_Int hypre_NodeRelaxSetZeroGuess ( void *relax_vdata, NALU_HYPRE_Int zero_guess );
NALU_HYPRE_Int hypre_NodeRelaxSetWeight ( void *relax_vdata, NALU_HYPRE_Real weight );
NALU_HYPRE_Int hypre_NodeRelaxSetNumNodesets ( void *relax_vdata, NALU_HYPRE_Int num_nodesets );
NALU_HYPRE_Int hypre_NodeRelaxSetNodeset ( void *relax_vdata, NALU_HYPRE_Int nodeset, NALU_HYPRE_Int nodeset_size,
                                      hypre_Index nodeset_stride, hypre_Index *nodeset_indices );
NALU_HYPRE_Int hypre_NodeRelaxSetNodesetRank ( void *relax_vdata, NALU_HYPRE_Int nodeset,
                                          NALU_HYPRE_Int nodeset_rank );
NALU_HYPRE_Int hypre_NodeRelaxSetTempVec ( void *relax_vdata, hypre_SStructPVector *t );

/* sstruct_amr_intercommunication.c */
NALU_HYPRE_Int hypre_SStructAMRInterCommunication ( hypre_SStructSendInfoData *sendinfo,
                                               hypre_SStructRecvInfoData *recvinfo, hypre_BoxArray *send_data_space,
                                               hypre_BoxArray *recv_data_space, NALU_HYPRE_Int num_values, MPI_Comm comm,
                                               hypre_CommPkg **comm_pkg_ptr );

/* sstruct_owninfo.c */
NALU_HYPRE_Int hypre_SStructIndexScaleF_C ( hypre_Index findex, hypre_Index index, hypre_Index stride,
                                       hypre_Index cindex );
NALU_HYPRE_Int hypre_SStructIndexScaleC_F ( hypre_Index cindex, hypre_Index index, hypre_Index stride,
                                       hypre_Index findex );
hypre_SStructOwnInfoData *hypre_SStructOwnInfo ( hypre_StructGrid *fgrid, hypre_StructGrid *cgrid,
                                                 hypre_BoxManager *cboxman, hypre_BoxManager *fboxman, hypre_Index rfactor );
NALU_HYPRE_Int hypre_SStructOwnInfoDataDestroy ( hypre_SStructOwnInfoData *owninfo_data );

/* sstruct_recvinfo.c */
hypre_SStructRecvInfoData *hypre_SStructRecvInfo ( hypre_StructGrid *cgrid,
                                                   hypre_BoxManager *fboxman, hypre_Index rfactor );
NALU_HYPRE_Int hypre_SStructRecvInfoDataDestroy ( hypre_SStructRecvInfoData *recvinfo_data );

/* sstruct_sendinfo.c */
hypre_SStructSendInfoData *hypre_SStructSendInfo ( hypre_StructGrid *fgrid,
                                                   hypre_BoxManager *cboxman, hypre_Index rfactor );
NALU_HYPRE_Int hypre_SStructSendInfoDataDestroy ( hypre_SStructSendInfoData *sendinfo_data );

/* sstruct_sharedDOFComm.c */
hypre_MaxwellOffProcRow *hypre_MaxwellOffProcRowCreate ( NALU_HYPRE_Int ncols );
NALU_HYPRE_Int hypre_MaxwellOffProcRowDestroy ( void *OffProcRow_vdata );
NALU_HYPRE_Int hypre_SStructSharedDOF_ParcsrMatRowsComm ( hypre_SStructGrid *grid, hypre_ParCSRMatrix *A,
                                                     NALU_HYPRE_Int *num_offprocrows_ptr, hypre_MaxwellOffProcRow ***OffProcRows_ptr );

/* sys_pfmg.c */
void *hypre_SysPFMGCreate ( MPI_Comm comm );
NALU_HYPRE_Int hypre_SysPFMGDestroy ( void *sys_pfmg_vdata );
NALU_HYPRE_Int hypre_SysPFMGSetTol ( void *sys_pfmg_vdata, NALU_HYPRE_Real tol );
NALU_HYPRE_Int hypre_SysPFMGSetMaxIter ( void *sys_pfmg_vdata, NALU_HYPRE_Int max_iter );
NALU_HYPRE_Int hypre_SysPFMGSetRelChange ( void *sys_pfmg_vdata, NALU_HYPRE_Int rel_change );
NALU_HYPRE_Int hypre_SysPFMGSetZeroGuess ( void *sys_pfmg_vdata, NALU_HYPRE_Int zero_guess );
NALU_HYPRE_Int hypre_SysPFMGSetRelaxType ( void *sys_pfmg_vdata, NALU_HYPRE_Int relax_type );
NALU_HYPRE_Int hypre_SysPFMGSetJacobiWeight ( void *sys_pfmg_vdata, NALU_HYPRE_Real weight );
NALU_HYPRE_Int hypre_SysPFMGSetNumPreRelax ( void *sys_pfmg_vdata, NALU_HYPRE_Int num_pre_relax );
NALU_HYPRE_Int hypre_SysPFMGSetNumPostRelax ( void *sys_pfmg_vdata, NALU_HYPRE_Int num_post_relax );
NALU_HYPRE_Int hypre_SysPFMGSetSkipRelax ( void *sys_pfmg_vdata, NALU_HYPRE_Int skip_relax );
NALU_HYPRE_Int hypre_SysPFMGSetDxyz ( void *sys_pfmg_vdata, NALU_HYPRE_Real *dxyz );
NALU_HYPRE_Int hypre_SysPFMGSetLogging ( void *sys_pfmg_vdata, NALU_HYPRE_Int logging );
NALU_HYPRE_Int hypre_SysPFMGSetPrintLevel ( void *sys_pfmg_vdata, NALU_HYPRE_Int print_level );
NALU_HYPRE_Int hypre_SysPFMGGetNumIterations ( void *sys_pfmg_vdata, NALU_HYPRE_Int *num_iterations );
NALU_HYPRE_Int hypre_SysPFMGPrintLogging ( void *sys_pfmg_vdata, NALU_HYPRE_Int myid );
NALU_HYPRE_Int hypre_SysPFMGGetFinalRelativeResidualNorm ( void *sys_pfmg_vdata,
                                                      NALU_HYPRE_Real *relative_residual_norm );

/* sys_pfmg_relax.c */
void *hypre_SysPFMGRelaxCreate ( MPI_Comm comm );
NALU_HYPRE_Int hypre_SysPFMGRelaxDestroy ( void *sys_pfmg_relax_vdata );
NALU_HYPRE_Int hypre_SysPFMGRelax ( void *sys_pfmg_relax_vdata, hypre_SStructPMatrix *A,
                               hypre_SStructPVector *b, hypre_SStructPVector *x );
NALU_HYPRE_Int hypre_SysPFMGRelaxSetup ( void *sys_pfmg_relax_vdata, hypre_SStructPMatrix *A,
                                    hypre_SStructPVector *b, hypre_SStructPVector *x );
NALU_HYPRE_Int hypre_SysPFMGRelaxSetType ( void *sys_pfmg_relax_vdata, NALU_HYPRE_Int relax_type );
NALU_HYPRE_Int hypre_SysPFMGRelaxSetJacobiWeight ( void *sys_pfmg_relax_vdata, NALU_HYPRE_Real weight );
NALU_HYPRE_Int hypre_SysPFMGRelaxSetPreRelax ( void *sys_pfmg_relax_vdata );
NALU_HYPRE_Int hypre_SysPFMGRelaxSetPostRelax ( void *sys_pfmg_relax_vdata );
NALU_HYPRE_Int hypre_SysPFMGRelaxSetTol ( void *sys_pfmg_relax_vdata, NALU_HYPRE_Real tol );
NALU_HYPRE_Int hypre_SysPFMGRelaxSetMaxIter ( void *sys_pfmg_relax_vdata, NALU_HYPRE_Int max_iter );
NALU_HYPRE_Int hypre_SysPFMGRelaxSetZeroGuess ( void *sys_pfmg_relax_vdata, NALU_HYPRE_Int zero_guess );
NALU_HYPRE_Int hypre_SysPFMGRelaxSetTempVec ( void *sys_pfmg_relax_vdata, hypre_SStructPVector *t );

/* sys_pfmg_setup.c */
NALU_HYPRE_Int hypre_SysPFMGSetup ( void *sys_pfmg_vdata, hypre_SStructMatrix *A_in,
                               hypre_SStructVector *b_in, hypre_SStructVector *x_in );
NALU_HYPRE_Int hypre_SysStructCoarsen ( hypre_SStructPGrid *fgrid, hypre_Index index, hypre_Index stride,
                                   NALU_HYPRE_Int prune, hypre_SStructPGrid **cgrid_ptr );

/* sys_pfmg_setup_interp.c */
hypre_SStructPMatrix *hypre_SysPFMGCreateInterpOp ( hypre_SStructPMatrix *A,
                                                    hypre_SStructPGrid *cgrid, NALU_HYPRE_Int cdir );
NALU_HYPRE_Int hypre_SysPFMGSetupInterpOp ( hypre_SStructPMatrix *A, NALU_HYPRE_Int cdir, hypre_Index findex,
                                       hypre_Index stride, hypre_SStructPMatrix *P );

/* sys_pfmg_setup_rap.c */
hypre_SStructPMatrix *hypre_SysPFMGCreateRAPOp ( hypre_SStructPMatrix *R, hypre_SStructPMatrix *A,
                                                 hypre_SStructPMatrix *P, hypre_SStructPGrid *coarse_grid, NALU_HYPRE_Int cdir );
NALU_HYPRE_Int hypre_SysPFMGSetupRAPOp ( hypre_SStructPMatrix *R, hypre_SStructPMatrix *A,
                                    hypre_SStructPMatrix *P, NALU_HYPRE_Int cdir, hypre_Index cindex, hypre_Index cstride,
                                    hypre_SStructPMatrix *Ac );

/* sys_pfmg_solve.c */
NALU_HYPRE_Int hypre_SysPFMGSolve ( void *sys_pfmg_vdata, hypre_SStructMatrix *A_in,
                               hypre_SStructVector *b_in, hypre_SStructVector *x_in );

/* sys_semi_interp.c */
NALU_HYPRE_Int hypre_SysSemiInterpCreate ( void **sys_interp_vdata_ptr );
NALU_HYPRE_Int hypre_SysSemiInterpSetup ( void *sys_interp_vdata, hypre_SStructPMatrix *P,
                                     NALU_HYPRE_Int P_stored_as_transpose, hypre_SStructPVector *xc, hypre_SStructPVector *e,
                                     hypre_Index cindex, hypre_Index findex, hypre_Index stride );
NALU_HYPRE_Int hypre_SysSemiInterp ( void *sys_interp_vdata, hypre_SStructPMatrix *P,
                                hypre_SStructPVector *xc, hypre_SStructPVector *e );
NALU_HYPRE_Int hypre_SysSemiInterpDestroy ( void *sys_interp_vdata );

/* sys_semi_restrict.c */
NALU_HYPRE_Int hypre_SysSemiRestrictCreate ( void **sys_restrict_vdata_ptr );
NALU_HYPRE_Int hypre_SysSemiRestrictSetup ( void *sys_restrict_vdata, hypre_SStructPMatrix *R,
                                       NALU_HYPRE_Int R_stored_as_transpose, hypre_SStructPVector *r, hypre_SStructPVector *rc,
                                       hypre_Index cindex, hypre_Index findex, hypre_Index stride );
NALU_HYPRE_Int hypre_SysSemiRestrict ( void *sys_restrict_vdata, hypre_SStructPMatrix *R,
                                  hypre_SStructPVector *r, hypre_SStructPVector *rc );
NALU_HYPRE_Int hypre_SysSemiRestrictDestroy ( void *sys_restrict_vdata );

#ifdef __cplusplus
}
#endif

#endif

