/******************************************************************************
 * Copyright (c) 1998 Lawrence Livermore National Security, LLC and other
 * HYPRE Project Developers. See the top-level COPYRIGHT file for details.
 *
 * SPDX-License-Identifier: (Apache-2.0 OR MIT)
 ******************************************************************************/

/******************************************************************************
 *
 * Header info for the Maxwell solver
 *
 *****************************************************************************/

#ifndef hypre_MAXWELL_HEADER
#define hypre_MAXWELL_HEADER

/*--------------------------------------------------------------------------
 * hypre_MaxwellData:
 *--------------------------------------------------------------------------*/

typedef struct
{
   MPI_Comm                comm;

   NALU_HYPRE_Real              tol;
   NALU_HYPRE_Int               max_iter;
   NALU_HYPRE_Int               rel_change;
   NALU_HYPRE_Int               zero_guess;
   NALU_HYPRE_Int               ndim;

   NALU_HYPRE_Int               num_pre_relax;  /* number of pre relaxation sweeps */
   NALU_HYPRE_Int               num_post_relax; /* number of post relaxation sweeps */

   NALU_HYPRE_Int               constant_coef;

   hypre_Index            *rfactor;

   hypre_SStructGrid     **egrid_l;

   NALU_HYPRE_IJMatrix          Aen;
   hypre_ParCSRMatrix    **Aen_l;

   /* these will be extracted from the amg_data structure. Note that there is no grid
      underlying these matrices and vectors if they are generated by the amg_setup.
      So, will be stored as Parcsr_matrices and Par_vectors. */
   hypre_SStructMatrix    *Ann;
   hypre_SStructVector    *bn;
   hypre_SStructVector    *xn;

   void                   *amg_vdata;
   hypre_ParCSRMatrix    **Ann_l;
   hypre_SStructStencil  **Ann_stencils;
   hypre_ParCSRMatrix    **Pn_l;
   hypre_ParCSRMatrix    **RnT_l;
   hypre_ParVector       **bn_l;
   hypre_ParVector       **xn_l;
   hypre_ParVector       **resn_l;
   hypre_ParVector       **en_l;
   hypre_ParVector       **nVtemp_l;
   hypre_ParVector       **nVtemp2_l;
   NALU_HYPRE_Int             **nCF_marker_l;
   NALU_HYPRE_Real             *nrelax_weight;
   NALU_HYPRE_Real             *nomega;
   NALU_HYPRE_Int               nrelax_type;
   NALU_HYPRE_Int               node_numlevels;

   hypre_ParCSRMatrix     *Tgrad;
   hypre_ParCSRMatrix     *T_transpose;

   /* edge data structure. These will have grids. */
   NALU_HYPRE_Int               edge_maxlevels;
   NALU_HYPRE_Int               edge_numlevels;
   hypre_ParCSRMatrix    **Aee_l;
   hypre_ParVector       **be_l;
   hypre_ParVector       **xe_l;
   hypre_ParVector       **rese_l;
   hypre_ParVector       **ee_l;
   hypre_ParVector       **eVtemp_l;
   hypre_ParVector       **eVtemp2_l;
   NALU_HYPRE_Int             **eCF_marker_l;
   NALU_HYPRE_Real             *erelax_weight;
   NALU_HYPRE_Real             *eomega;
   NALU_HYPRE_Int               erelax_type;

   /* edge data structure. These will have no grid. */
   hypre_IJMatrix        **Pe_l;
   hypre_IJMatrix        **ReT_l;
   NALU_HYPRE_Int             **BdryRanks_l;
   NALU_HYPRE_Int              *BdryRanksCnts_l;

   /* edge-node data structure. These will have grids. */
   NALU_HYPRE_Int               en_numlevels;

   /* log info (always logged) */
   NALU_HYPRE_Int               num_iterations;
   NALU_HYPRE_Int               time_index;

   /* additional log info (logged when `logging' > 0) */
   NALU_HYPRE_Int               print_level;
   NALU_HYPRE_Int               logging;
   NALU_HYPRE_Real             *norms;
   NALU_HYPRE_Real             *rel_norms;

} hypre_MaxwellData;

#endif
